// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC87T-JnqaNj7QvUDHqEMHDwlep4guhnYU',
    appId: '1:911449039529:web:dd22f2b78ffacd9514bfb8',
    messagingSenderId: '911449039529',
    projectId: 'fruit-app-789fd',
    authDomain: 'fruit-app-789fd.firebaseapp.com',
    databaseURL: 'https://fruit-app-789fd-default-rtdb.firebaseio.com',
    storageBucket: 'fruit-app-789fd.firebasestorage.app',
    measurementId: 'G-Q352Y5ZBBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOe7aFnGvAvXmhfrz7vdSwcFoDRuP1nqs',
    appId: '1:911449039529:android:bb68fa7c459e392d14bfb8',
    messagingSenderId: '911449039529',
    projectId: 'fruit-app-789fd',
    databaseURL: 'https://fruit-app-789fd-default-rtdb.firebaseio.com',
    storageBucket: 'fruit-app-789fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKFdd1fuCPvWYp2rVBf1k7W6Gwj_nFZ1Q',
    appId: '1:911449039529:ios:73b8a80999f0bbab14bfb8',
    messagingSenderId: '911449039529',
    projectId: 'fruit-app-789fd',
    databaseURL: 'https://fruit-app-789fd-default-rtdb.firebaseio.com',
    storageBucket: 'fruit-app-789fd.firebasestorage.app',
    androidClientId: '911449039529-8a5obnc1h6v4va072t74ll9utdc7t961.apps.googleusercontent.com',
    iosClientId: '911449039529-6p47qgu70ndlsc0lv5pvvqc5usv693ju.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKFdd1fuCPvWYp2rVBf1k7W6Gwj_nFZ1Q',
    appId: '1:911449039529:ios:73b8a80999f0bbab14bfb8',
    messagingSenderId: '911449039529',
    projectId: 'fruit-app-789fd',
    databaseURL: 'https://fruit-app-789fd-default-rtdb.firebaseio.com',
    storageBucket: 'fruit-app-789fd.firebasestorage.app',
    androidClientId: '911449039529-8a5obnc1h6v4va072t74ll9utdc7t961.apps.googleusercontent.com',
    iosClientId: '911449039529-6p47qgu70ndlsc0lv5pvvqc5usv693ju.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitApp',
  );
}
